### ISSUE TITLE
无法出现对应的条目

### ISSUE THREAD

**Issue by Bluewaterhua** [huamang/SiYuan-Search-workflow#1]
在一开始我尝试了1.2但是无法生成对应的东西 只能够跳转谷歌进行 搜索 是不是还需要额外的配置呢
<img width="642" alt="image" src="https://github.com/huamang/SiYuan-Search-workflow/assets/47163968/6ed15809-26d9-4679-858b-e33a3f7e89bd">

**Comment by huamang** [comment]
请确保有python3环境，脚本是基于python3编写的，你可以打开Alfred的debug去看看报错

**Comment by Bluewaterhua** [comment]
谢谢你，我查看了报错后 发现了bug 不过目前还没有修复 不知道是否和python的版本有关
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=6806): Max retries exceeded with url: /api/search/fullTextSearchBlock (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104816b50>: Failed to establish a new connection: [Errno 61] Connection refused'))`
<img width="845" alt="image" src="https://github.com/huamang/SiYuan-Search-workflow/assets/47163968/ccc6ddd3-669e-4873-ab8b-6878f80f6f6b">

**Comment by Bluewaterhua** [comment]
你好，再次感谢你提供的插件，对我帮助很大，我已经修复这个bug，我猜测原因是一开始在报错时我对6806端口的多次访问导致requests出现的问题，因此我将serch.py中的端口号更换为了思源每次提供的随机端口之后可以正常运行，我重启电脑后，6806端口已经可以正常运行。

**Comment by Bluewaterhua** [comment]
请问你有思源开发的具体的api么 我发现这个api/search/fullTextSearchBlock是在kernel api中 并未在官方的api中出现，你有完整的api文档么😘

**Comment by huamang** [comment]
> 请问你有思源开发的具体的api么 我发现这个api/search/fullTextSearchBlock是在kernel api中 并未在官方的api中出现，你有完整的api文档么😘

我没有去看官方文档，这个api是我直接抓包分析的(∩_∩)

**Comment by Bluewaterhua** [comment]
非常感谢 我怎么没想到抓包 谢谢谢谢！！！





------------------ 原始邮件 ------------------
From: SilentStone ***@***.***&gt;
发送时间: 05/18/2023, 23:43
To: huamang/SiYuan-Search-workflow ***@***.***&gt;
抄送: Bluewaterhua ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [huamang/SiYuan-Search-workflow] 无法出现对应的条目 (Issue #1)





  
请问你有思源开发的具体的api么 我发现这个api/search/fullTextSearchBlock是在kernel api中 并未在官方的api中出现，你有完整的api文档么😘
  
我没有去看官方文档，这个api是我直接抓包分析的(∩_∩)
